import './globals.css'

export const metadata = {
  title: 'HypeWheels',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className='relative'>
        {children}
      </body>
    </html>
  )
}
